//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.SudokuApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arrow()
        {
            this.Cell2 = new HashSet<Cell>();
        }
    
        public long arrowId { get; set; }
        public long sudokuId { get; set; }
        public long start_cell { get; set; }
        public long end_cell { get; set; }
    
        public virtual Cell Cell { get; set; }
        public virtual Cell Cell1 { get; set; }
        public virtual Sudoku Sudoku { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cell> Cell2 { get; set; }
    }
}
