//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.SudokuApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public long userId { get; set; }
        public long tournamentId { get; set; }
        public System.TimeSpan time { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual Users Users { get; set; }
    }
}
