//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.SudokuApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long sudokuId { get; set; }
        public long usrId { get; set; }
        public Nullable<int> review_value { get; set; }
    
        public virtual Sudoku Sudoku { get; set; }
        public virtual Users Users { get; set; }
    }
}
