//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.SudokuApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sudokuapp : DbContext
    {
        public sudokuapp()
            : base("name=sudokuapp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arrow> Arrow { get; set; }
        public virtual DbSet<Cell> Cell { get; set; }
        public virtual DbSet<Killer_box> Killer_box { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Sudoku> Sudoku { get; set; }
        public virtual DbSet<Thermo> Thermo { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
